language: minimal

services:
  - docker

script:
  - docker build -t weidong/cpp-playground .
  - docker run -v $(pwd):/project weidong/cpp-playground /bin/sh -c "cd /project && mkdir -p build && cd build && cmake .. && make && ctest --verbose"
