language: minimal

services:
  - docker

install:
  - docker build -t weidong/cpp-playground .

script:
  - docker run -v $(pwd):/app weidong/cpp-playground /bin/sh -c "cd /app && ./scripts/run_build_and_test.sh"


