language: minimal

services:
  - docker

script:
  - docker build -t weidong/cpp-playground .
  - docker run weidong/cpp-playground "cd /project && mkdir -p build && cd build && cmake .. && make && ctest --verbose"
