pipeline {
    agent {
        docker {
            image 'madduci/docker-cpp-env:latest'
            args '-v .:/project'
        }
    }
    environment {
        CI = 'true'
    }
    stages {        
        stage('Build') {
            steps {
                sh 'mkdir -p build && cd build && cmake .. && make'
            }
        }
        stage('Test') {
            steps {
                sh 'cd build && cmake --build . --target test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo "Deploy to be added."'
            }
        }        
    }
}
