name: cpp-playground

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Configure
      run: mkdir build && cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cd build && ninja
    - name: Test
      run: cd build && ctest
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
