name: cpp-playground

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: build docker
    #  run: docker build -t weidonglianlian/cpp-playground .
    -name: download docker
      run: docker pull weidonglian/cpp-playground:v1
    - name: run build and test with docker
      run: docker run -v $(pwd):/app weidong/cpp-playgroundlian:v1 /bin/sh -c "cd /app && ./scripts/run_build_and_test.sh"
